name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Set up env
        run: |
          # Github is broken.
          # https://github.com/actions/setup-go/issues/14
          # https://github.com/actions/setup-go/issues/27
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci
